name: CDK Deploy

on:
  push:
    branches:
      - main
      - develop
      - staging # hoặc nhánh bạn muốn tự động deploy

jobs:
  deploy:
    if: github.ref == 'refs/heads/' + matrix.branch
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - branch: main
            env: prod
          - branch: develop
            env: dev
          - branch: staging
            env: staging

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'   # hoặc version bạn dùng

      - name: Install dependencies
        run: npm install

      - name: Deploy CDK stack
        run: npx cdk deploy --context env=${{ matrix.env }} --require-approval=never
